/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: maxpanysh (https://sketchfab.com/maxpanysh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/silent-ash-bc44272e8c1047148b33c913e659fcfa
Title: Silent Ash
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.9}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.002, 1, 0.003]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Bunny} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.Skateboard} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
